// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commodity_price.proto

package com.panjin.grpc.errorhandling;

/**
 * Protobuf type {@code commodityprice.CommodityQuote}
 */
public final class CommodityQuote extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:commodityprice.CommodityQuote)
    CommodityQuoteOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CommodityQuote.newBuilder() to construct.
  private CommodityQuote(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CommodityQuote() {
    commodityName_ = "";
    producerName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CommodityQuote();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.panjin.grpc.errorhandling.CommodityPriceProto.internal_static_commodityprice_CommodityQuote_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.panjin.grpc.errorhandling.CommodityPriceProto.internal_static_commodityprice_CommodityQuote_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.panjin.grpc.errorhandling.CommodityQuote.class, com.panjin.grpc.errorhandling.CommodityQuote.Builder.class);
  }

  public static final int COMMODITY_NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object commodityName_ = "";
  /**
   * <code>string commodity_name = 1;</code>
   * @return The commodityName.
   */
  @java.lang.Override
  public java.lang.String getCommodityName() {
    java.lang.Object ref = commodityName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      commodityName_ = s;
      return s;
    }
  }
  /**
   * <code>string commodity_name = 1;</code>
   * @return The bytes for commodityName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCommodityNameBytes() {
    java.lang.Object ref = commodityName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      commodityName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRODUCER_NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object producerName_ = "";
  /**
   * <code>string producer_name = 2;</code>
   * @return The producerName.
   */
  @java.lang.Override
  public java.lang.String getProducerName() {
    java.lang.Object ref = producerName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      producerName_ = s;
      return s;
    }
  }
  /**
   * <code>string producer_name = 2;</code>
   * @return The bytes for producerName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProducerNameBytes() {
    java.lang.Object ref = producerName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      producerName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRICE_FIELD_NUMBER = 3;
  private double price_ = 0D;
  /**
   * <code>double price = 3;</code>
   * @return The price.
   */
  @java.lang.Override
  public double getPrice() {
    return price_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(commodityName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, commodityName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(producerName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, producerName_);
    }
    if (java.lang.Double.doubleToRawLongBits(price_) != 0) {
      output.writeDouble(3, price_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(commodityName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, commodityName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(producerName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, producerName_);
    }
    if (java.lang.Double.doubleToRawLongBits(price_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, price_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.panjin.grpc.errorhandling.CommodityQuote)) {
      return super.equals(obj);
    }
    com.panjin.grpc.errorhandling.CommodityQuote other = (com.panjin.grpc.errorhandling.CommodityQuote) obj;

    if (!getCommodityName()
        .equals(other.getCommodityName())) return false;
    if (!getProducerName()
        .equals(other.getProducerName())) return false;
    if (java.lang.Double.doubleToLongBits(getPrice())
        != java.lang.Double.doubleToLongBits(
            other.getPrice())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COMMODITY_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getCommodityName().hashCode();
    hash = (37 * hash) + PRODUCER_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getProducerName().hashCode();
    hash = (37 * hash) + PRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPrice()));
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.panjin.grpc.errorhandling.CommodityQuote parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.panjin.grpc.errorhandling.CommodityQuote parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.panjin.grpc.errorhandling.CommodityQuote parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.panjin.grpc.errorhandling.CommodityQuote parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.panjin.grpc.errorhandling.CommodityQuote parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.panjin.grpc.errorhandling.CommodityQuote parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.panjin.grpc.errorhandling.CommodityQuote parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.panjin.grpc.errorhandling.CommodityQuote parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.panjin.grpc.errorhandling.CommodityQuote parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.panjin.grpc.errorhandling.CommodityQuote parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.panjin.grpc.errorhandling.CommodityQuote parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.panjin.grpc.errorhandling.CommodityQuote parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.panjin.grpc.errorhandling.CommodityQuote prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code commodityprice.CommodityQuote}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:commodityprice.CommodityQuote)
      com.panjin.grpc.errorhandling.CommodityQuoteOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.panjin.grpc.errorhandling.CommodityPriceProto.internal_static_commodityprice_CommodityQuote_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.panjin.grpc.errorhandling.CommodityPriceProto.internal_static_commodityprice_CommodityQuote_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.panjin.grpc.errorhandling.CommodityQuote.class, com.panjin.grpc.errorhandling.CommodityQuote.Builder.class);
    }

    // Construct using com.panjin.grpc.errorhandling.CommodityQuote.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      commodityName_ = "";
      producerName_ = "";
      price_ = 0D;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.panjin.grpc.errorhandling.CommodityPriceProto.internal_static_commodityprice_CommodityQuote_descriptor;
    }

    @java.lang.Override
    public com.panjin.grpc.errorhandling.CommodityQuote getDefaultInstanceForType() {
      return com.panjin.grpc.errorhandling.CommodityQuote.getDefaultInstance();
    }

    @java.lang.Override
    public com.panjin.grpc.errorhandling.CommodityQuote build() {
      com.panjin.grpc.errorhandling.CommodityQuote result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.panjin.grpc.errorhandling.CommodityQuote buildPartial() {
      com.panjin.grpc.errorhandling.CommodityQuote result = new com.panjin.grpc.errorhandling.CommodityQuote(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.panjin.grpc.errorhandling.CommodityQuote result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.commodityName_ = commodityName_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.producerName_ = producerName_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.price_ = price_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.panjin.grpc.errorhandling.CommodityQuote) {
        return mergeFrom((com.panjin.grpc.errorhandling.CommodityQuote)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.panjin.grpc.errorhandling.CommodityQuote other) {
      if (other == com.panjin.grpc.errorhandling.CommodityQuote.getDefaultInstance()) return this;
      if (!other.getCommodityName().isEmpty()) {
        commodityName_ = other.commodityName_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getProducerName().isEmpty()) {
        producerName_ = other.producerName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getPrice() != 0D) {
        setPrice(other.getPrice());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              commodityName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              producerName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 25: {
              price_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object commodityName_ = "";
    /**
     * <code>string commodity_name = 1;</code>
     * @return The commodityName.
     */
    public java.lang.String getCommodityName() {
      java.lang.Object ref = commodityName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        commodityName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string commodity_name = 1;</code>
     * @return The bytes for commodityName.
     */
    public com.google.protobuf.ByteString
        getCommodityNameBytes() {
      java.lang.Object ref = commodityName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        commodityName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string commodity_name = 1;</code>
     * @param value The commodityName to set.
     * @return This builder for chaining.
     */
    public Builder setCommodityName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      commodityName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string commodity_name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommodityName() {
      commodityName_ = getDefaultInstance().getCommodityName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string commodity_name = 1;</code>
     * @param value The bytes for commodityName to set.
     * @return This builder for chaining.
     */
    public Builder setCommodityNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      commodityName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object producerName_ = "";
    /**
     * <code>string producer_name = 2;</code>
     * @return The producerName.
     */
    public java.lang.String getProducerName() {
      java.lang.Object ref = producerName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        producerName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string producer_name = 2;</code>
     * @return The bytes for producerName.
     */
    public com.google.protobuf.ByteString
        getProducerNameBytes() {
      java.lang.Object ref = producerName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        producerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string producer_name = 2;</code>
     * @param value The producerName to set.
     * @return This builder for chaining.
     */
    public Builder setProducerName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      producerName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string producer_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearProducerName() {
      producerName_ = getDefaultInstance().getProducerName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string producer_name = 2;</code>
     * @param value The bytes for producerName to set.
     * @return This builder for chaining.
     */
    public Builder setProducerNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      producerName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private double price_ ;
    /**
     * <code>double price = 3;</code>
     * @return The price.
     */
    @java.lang.Override
    public double getPrice() {
      return price_;
    }
    /**
     * <code>double price = 3;</code>
     * @param value The price to set.
     * @return This builder for chaining.
     */
    public Builder setPrice(double value) {
      
      price_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>double price = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrice() {
      bitField0_ = (bitField0_ & ~0x00000004);
      price_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:commodityprice.CommodityQuote)
  }

  // @@protoc_insertion_point(class_scope:commodityprice.CommodityQuote)
  private static final com.panjin.grpc.errorhandling.CommodityQuote DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.panjin.grpc.errorhandling.CommodityQuote();
  }

  public static com.panjin.grpc.errorhandling.CommodityQuote getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CommodityQuote>
      PARSER = new com.google.protobuf.AbstractParser<CommodityQuote>() {
    @java.lang.Override
    public CommodityQuote parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CommodityQuote> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CommodityQuote> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.panjin.grpc.errorhandling.CommodityQuote getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

