// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commodity_price.proto

package com.panjin.grpc.errorhandling;

public interface CommodityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:commodityprice.Commodity)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string access_token = 1;</code>
   * @return The accessToken.
   */
  java.lang.String getAccessToken();
  /**
   * <code>string access_token = 1;</code>
   * @return The bytes for accessToken.
   */
  com.google.protobuf.ByteString
      getAccessTokenBytes();

  /**
   * <code>string commodity_name = 2;</code>
   * @return The commodityName.
   */
  java.lang.String getCommodityName();
  /**
   * <code>string commodity_name = 2;</code>
   * @return The bytes for commodityName.
   */
  com.google.protobuf.ByteString
      getCommodityNameBytes();
}
