// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commodity_price.proto

package com.panjin.grpc.errorhandling;

public final class CommodityPriceProto {
  private CommodityPriceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_commodityprice_Commodity_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_commodityprice_Commodity_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_commodityprice_CommodityQuote_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_commodityprice_CommodityQuote_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_commodityprice_ErrorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_commodityprice_ErrorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_commodityprice_StreamingCommodityQuote_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_commodityprice_StreamingCommodityQuote_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025commodity_price.proto\022\016commodityprice\032" +
      "\027google/rpc/status.proto\"9\n\tCommodity\022\024\n" +
      "\014access_token\030\001 \001(\t\022\026\n\016commodity_name\030\002 " +
      "\001(\t\"N\n\016CommodityQuote\022\026\n\016commodity_name\030" +
      "\001 \001(\t\022\025\n\rproducer_name\030\002 \001(\t\022\r\n\005price\030\003 " +
      "\001(\001\"m\n\rErrorResponse\022\026\n\016commodity_name\030\001" +
      " \001(\t\022\024\n\014access_token\030\002 \001(\t\022\026\n\016expected_t" +
      "oken\030\003 \001(\t\022\026\n\016expected_value\030\004 \001(\t\"\204\001\n\027S" +
      "treamingCommodityQuote\0228\n\016comodity_quote" +
      "\030\001 \001(\0132\036.commodityprice.CommodityQuoteH\000" +
      "\022$\n\006status\030\002 \001(\0132\022.google.rpc.StatusH\000B\t" +
      "\n\007message2\325\001\n\026CommodityPriceProvider\022T\n\025" +
      "getBestCommodityPrice\022\031.commodityprice.C" +
      "ommodity\032\036.commodityprice.CommodityQuote" +
      "\"\000\022e\n\031bidirectionalListOfPrices\022\031.commod" +
      "ityprice.Commodity\032\'.commodityprice.Stre" +
      "amingCommodityQuote\"\000(\0010\001B<\n\035com.panjin." +
      "grpc.errorhandlingB\023CommodityPriceProtoP" +
      "\001\242\002\003RTGb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.rpc.StatusProto.getDescriptor(),
        });
    internal_static_commodityprice_Commodity_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_commodityprice_Commodity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_commodityprice_Commodity_descriptor,
        new java.lang.String[] { "AccessToken", "CommodityName", });
    internal_static_commodityprice_CommodityQuote_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_commodityprice_CommodityQuote_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_commodityprice_CommodityQuote_descriptor,
        new java.lang.String[] { "CommodityName", "ProducerName", "Price", });
    internal_static_commodityprice_ErrorResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_commodityprice_ErrorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_commodityprice_ErrorResponse_descriptor,
        new java.lang.String[] { "CommodityName", "AccessToken", "ExpectedToken", "ExpectedValue", });
    internal_static_commodityprice_StreamingCommodityQuote_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_commodityprice_StreamingCommodityQuote_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_commodityprice_StreamingCommodityQuote_descriptor,
        new java.lang.String[] { "ComodityQuote", "Status", "Message", });
    com.google.rpc.StatusProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
