// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commodity_price.proto

package com.panjin.grpc.errorhandling;

public interface ErrorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:commodityprice.ErrorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string commodity_name = 1;</code>
   * @return The commodityName.
   */
  java.lang.String getCommodityName();
  /**
   * <code>string commodity_name = 1;</code>
   * @return The bytes for commodityName.
   */
  com.google.protobuf.ByteString
      getCommodityNameBytes();

  /**
   * <code>string access_token = 2;</code>
   * @return The accessToken.
   */
  java.lang.String getAccessToken();
  /**
   * <code>string access_token = 2;</code>
   * @return The bytes for accessToken.
   */
  com.google.protobuf.ByteString
      getAccessTokenBytes();

  /**
   * <code>string expected_token = 3;</code>
   * @return The expectedToken.
   */
  java.lang.String getExpectedToken();
  /**
   * <code>string expected_token = 3;</code>
   * @return The bytes for expectedToken.
   */
  com.google.protobuf.ByteString
      getExpectedTokenBytes();

  /**
   * <code>string expected_value = 4;</code>
   * @return The expectedValue.
   */
  java.lang.String getExpectedValue();
  /**
   * <code>string expected_value = 4;</code>
   * @return The bytes for expectedValue.
   */
  com.google.protobuf.ByteString
      getExpectedValueBytes();
}
