// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commodity_price.proto

package com.panjin.grpc.errorhandling;

/**
 * Protobuf type {@code commodityprice.StreamingCommodityQuote}
 */
public final class StreamingCommodityQuote extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:commodityprice.StreamingCommodityQuote)
    StreamingCommodityQuoteOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StreamingCommodityQuote.newBuilder() to construct.
  private StreamingCommodityQuote(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StreamingCommodityQuote() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StreamingCommodityQuote();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.panjin.grpc.errorhandling.CommodityPriceProto.internal_static_commodityprice_StreamingCommodityQuote_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.panjin.grpc.errorhandling.CommodityPriceProto.internal_static_commodityprice_StreamingCommodityQuote_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.panjin.grpc.errorhandling.StreamingCommodityQuote.class, com.panjin.grpc.errorhandling.StreamingCommodityQuote.Builder.class);
  }

  private int messageCase_ = 0;
  private java.lang.Object message_;
  public enum MessageCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    COMODITY_QUOTE(1),
    STATUS(2),
    MESSAGE_NOT_SET(0);
    private final int value;
    private MessageCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageCase valueOf(int value) {
      return forNumber(value);
    }

    public static MessageCase forNumber(int value) {
      switch (value) {
        case 1: return COMODITY_QUOTE;
        case 2: return STATUS;
        case 0: return MESSAGE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public MessageCase
  getMessageCase() {
    return MessageCase.forNumber(
        messageCase_);
  }

  public static final int COMODITY_QUOTE_FIELD_NUMBER = 1;
  /**
   * <code>.commodityprice.CommodityQuote comodity_quote = 1;</code>
   * @return Whether the comodityQuote field is set.
   */
  @java.lang.Override
  public boolean hasComodityQuote() {
    return messageCase_ == 1;
  }
  /**
   * <code>.commodityprice.CommodityQuote comodity_quote = 1;</code>
   * @return The comodityQuote.
   */
  @java.lang.Override
  public com.panjin.grpc.errorhandling.CommodityQuote getComodityQuote() {
    if (messageCase_ == 1) {
       return (com.panjin.grpc.errorhandling.CommodityQuote) message_;
    }
    return com.panjin.grpc.errorhandling.CommodityQuote.getDefaultInstance();
  }
  /**
   * <code>.commodityprice.CommodityQuote comodity_quote = 1;</code>
   */
  @java.lang.Override
  public com.panjin.grpc.errorhandling.CommodityQuoteOrBuilder getComodityQuoteOrBuilder() {
    if (messageCase_ == 1) {
       return (com.panjin.grpc.errorhandling.CommodityQuote) message_;
    }
    return com.panjin.grpc.errorhandling.CommodityQuote.getDefaultInstance();
  }

  public static final int STATUS_FIELD_NUMBER = 2;
  /**
   * <code>.google.rpc.Status status = 2;</code>
   * @return Whether the status field is set.
   */
  @java.lang.Override
  public boolean hasStatus() {
    return messageCase_ == 2;
  }
  /**
   * <code>.google.rpc.Status status = 2;</code>
   * @return The status.
   */
  @java.lang.Override
  public com.google.rpc.Status getStatus() {
    if (messageCase_ == 2) {
       return (com.google.rpc.Status) message_;
    }
    return com.google.rpc.Status.getDefaultInstance();
  }
  /**
   * <code>.google.rpc.Status status = 2;</code>
   */
  @java.lang.Override
  public com.google.rpc.StatusOrBuilder getStatusOrBuilder() {
    if (messageCase_ == 2) {
       return (com.google.rpc.Status) message_;
    }
    return com.google.rpc.Status.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (messageCase_ == 1) {
      output.writeMessage(1, (com.panjin.grpc.errorhandling.CommodityQuote) message_);
    }
    if (messageCase_ == 2) {
      output.writeMessage(2, (com.google.rpc.Status) message_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (messageCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.panjin.grpc.errorhandling.CommodityQuote) message_);
    }
    if (messageCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.google.rpc.Status) message_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.panjin.grpc.errorhandling.StreamingCommodityQuote)) {
      return super.equals(obj);
    }
    com.panjin.grpc.errorhandling.StreamingCommodityQuote other = (com.panjin.grpc.errorhandling.StreamingCommodityQuote) obj;

    if (!getMessageCase().equals(other.getMessageCase())) return false;
    switch (messageCase_) {
      case 1:
        if (!getComodityQuote()
            .equals(other.getComodityQuote())) return false;
        break;
      case 2:
        if (!getStatus()
            .equals(other.getStatus())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (messageCase_) {
      case 1:
        hash = (37 * hash) + COMODITY_QUOTE_FIELD_NUMBER;
        hash = (53 * hash) + getComodityQuote().hashCode();
        break;
      case 2:
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + getStatus().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.panjin.grpc.errorhandling.StreamingCommodityQuote parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.panjin.grpc.errorhandling.StreamingCommodityQuote parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.panjin.grpc.errorhandling.StreamingCommodityQuote parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.panjin.grpc.errorhandling.StreamingCommodityQuote parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.panjin.grpc.errorhandling.StreamingCommodityQuote parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.panjin.grpc.errorhandling.StreamingCommodityQuote parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.panjin.grpc.errorhandling.StreamingCommodityQuote parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.panjin.grpc.errorhandling.StreamingCommodityQuote parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.panjin.grpc.errorhandling.StreamingCommodityQuote parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.panjin.grpc.errorhandling.StreamingCommodityQuote parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.panjin.grpc.errorhandling.StreamingCommodityQuote parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.panjin.grpc.errorhandling.StreamingCommodityQuote parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.panjin.grpc.errorhandling.StreamingCommodityQuote prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code commodityprice.StreamingCommodityQuote}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:commodityprice.StreamingCommodityQuote)
      com.panjin.grpc.errorhandling.StreamingCommodityQuoteOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.panjin.grpc.errorhandling.CommodityPriceProto.internal_static_commodityprice_StreamingCommodityQuote_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.panjin.grpc.errorhandling.CommodityPriceProto.internal_static_commodityprice_StreamingCommodityQuote_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.panjin.grpc.errorhandling.StreamingCommodityQuote.class, com.panjin.grpc.errorhandling.StreamingCommodityQuote.Builder.class);
    }

    // Construct using com.panjin.grpc.errorhandling.StreamingCommodityQuote.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (comodityQuoteBuilder_ != null) {
        comodityQuoteBuilder_.clear();
      }
      if (statusBuilder_ != null) {
        statusBuilder_.clear();
      }
      messageCase_ = 0;
      message_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.panjin.grpc.errorhandling.CommodityPriceProto.internal_static_commodityprice_StreamingCommodityQuote_descriptor;
    }

    @java.lang.Override
    public com.panjin.grpc.errorhandling.StreamingCommodityQuote getDefaultInstanceForType() {
      return com.panjin.grpc.errorhandling.StreamingCommodityQuote.getDefaultInstance();
    }

    @java.lang.Override
    public com.panjin.grpc.errorhandling.StreamingCommodityQuote build() {
      com.panjin.grpc.errorhandling.StreamingCommodityQuote result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.panjin.grpc.errorhandling.StreamingCommodityQuote buildPartial() {
      com.panjin.grpc.errorhandling.StreamingCommodityQuote result = new com.panjin.grpc.errorhandling.StreamingCommodityQuote(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.panjin.grpc.errorhandling.StreamingCommodityQuote result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(com.panjin.grpc.errorhandling.StreamingCommodityQuote result) {
      result.messageCase_ = messageCase_;
      result.message_ = this.message_;
      if (messageCase_ == 1 &&
          comodityQuoteBuilder_ != null) {
        result.message_ = comodityQuoteBuilder_.build();
      }
      if (messageCase_ == 2 &&
          statusBuilder_ != null) {
        result.message_ = statusBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.panjin.grpc.errorhandling.StreamingCommodityQuote) {
        return mergeFrom((com.panjin.grpc.errorhandling.StreamingCommodityQuote)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.panjin.grpc.errorhandling.StreamingCommodityQuote other) {
      if (other == com.panjin.grpc.errorhandling.StreamingCommodityQuote.getDefaultInstance()) return this;
      switch (other.getMessageCase()) {
        case COMODITY_QUOTE: {
          mergeComodityQuote(other.getComodityQuote());
          break;
        }
        case STATUS: {
          mergeStatus(other.getStatus());
          break;
        }
        case MESSAGE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getComodityQuoteFieldBuilder().getBuilder(),
                  extensionRegistry);
              messageCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getStatusFieldBuilder().getBuilder(),
                  extensionRegistry);
              messageCase_ = 2;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int messageCase_ = 0;
    private java.lang.Object message_;
    public MessageCase
        getMessageCase() {
      return MessageCase.forNumber(
          messageCase_);
    }

    public Builder clearMessage() {
      messageCase_ = 0;
      message_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilderV3<
        com.panjin.grpc.errorhandling.CommodityQuote, com.panjin.grpc.errorhandling.CommodityQuote.Builder, com.panjin.grpc.errorhandling.CommodityQuoteOrBuilder> comodityQuoteBuilder_;
    /**
     * <code>.commodityprice.CommodityQuote comodity_quote = 1;</code>
     * @return Whether the comodityQuote field is set.
     */
    @java.lang.Override
    public boolean hasComodityQuote() {
      return messageCase_ == 1;
    }
    /**
     * <code>.commodityprice.CommodityQuote comodity_quote = 1;</code>
     * @return The comodityQuote.
     */
    @java.lang.Override
    public com.panjin.grpc.errorhandling.CommodityQuote getComodityQuote() {
      if (comodityQuoteBuilder_ == null) {
        if (messageCase_ == 1) {
          return (com.panjin.grpc.errorhandling.CommodityQuote) message_;
        }
        return com.panjin.grpc.errorhandling.CommodityQuote.getDefaultInstance();
      } else {
        if (messageCase_ == 1) {
          return comodityQuoteBuilder_.getMessage();
        }
        return com.panjin.grpc.errorhandling.CommodityQuote.getDefaultInstance();
      }
    }
    /**
     * <code>.commodityprice.CommodityQuote comodity_quote = 1;</code>
     */
    public Builder setComodityQuote(com.panjin.grpc.errorhandling.CommodityQuote value) {
      if (comodityQuoteBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
        onChanged();
      } else {
        comodityQuoteBuilder_.setMessage(value);
      }
      messageCase_ = 1;
      return this;
    }
    /**
     * <code>.commodityprice.CommodityQuote comodity_quote = 1;</code>
     */
    public Builder setComodityQuote(
        com.panjin.grpc.errorhandling.CommodityQuote.Builder builderForValue) {
      if (comodityQuoteBuilder_ == null) {
        message_ = builderForValue.build();
        onChanged();
      } else {
        comodityQuoteBuilder_.setMessage(builderForValue.build());
      }
      messageCase_ = 1;
      return this;
    }
    /**
     * <code>.commodityprice.CommodityQuote comodity_quote = 1;</code>
     */
    public Builder mergeComodityQuote(com.panjin.grpc.errorhandling.CommodityQuote value) {
      if (comodityQuoteBuilder_ == null) {
        if (messageCase_ == 1 &&
            message_ != com.panjin.grpc.errorhandling.CommodityQuote.getDefaultInstance()) {
          message_ = com.panjin.grpc.errorhandling.CommodityQuote.newBuilder((com.panjin.grpc.errorhandling.CommodityQuote) message_)
              .mergeFrom(value).buildPartial();
        } else {
          message_ = value;
        }
        onChanged();
      } else {
        if (messageCase_ == 1) {
          comodityQuoteBuilder_.mergeFrom(value);
        } else {
          comodityQuoteBuilder_.setMessage(value);
        }
      }
      messageCase_ = 1;
      return this;
    }
    /**
     * <code>.commodityprice.CommodityQuote comodity_quote = 1;</code>
     */
    public Builder clearComodityQuote() {
      if (comodityQuoteBuilder_ == null) {
        if (messageCase_ == 1) {
          messageCase_ = 0;
          message_ = null;
          onChanged();
        }
      } else {
        if (messageCase_ == 1) {
          messageCase_ = 0;
          message_ = null;
        }
        comodityQuoteBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.commodityprice.CommodityQuote comodity_quote = 1;</code>
     */
    public com.panjin.grpc.errorhandling.CommodityQuote.Builder getComodityQuoteBuilder() {
      return getComodityQuoteFieldBuilder().getBuilder();
    }
    /**
     * <code>.commodityprice.CommodityQuote comodity_quote = 1;</code>
     */
    @java.lang.Override
    public com.panjin.grpc.errorhandling.CommodityQuoteOrBuilder getComodityQuoteOrBuilder() {
      if ((messageCase_ == 1) && (comodityQuoteBuilder_ != null)) {
        return comodityQuoteBuilder_.getMessageOrBuilder();
      } else {
        if (messageCase_ == 1) {
          return (com.panjin.grpc.errorhandling.CommodityQuote) message_;
        }
        return com.panjin.grpc.errorhandling.CommodityQuote.getDefaultInstance();
      }
    }
    /**
     * <code>.commodityprice.CommodityQuote comodity_quote = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.panjin.grpc.errorhandling.CommodityQuote, com.panjin.grpc.errorhandling.CommodityQuote.Builder, com.panjin.grpc.errorhandling.CommodityQuoteOrBuilder> 
        getComodityQuoteFieldBuilder() {
      if (comodityQuoteBuilder_ == null) {
        if (!(messageCase_ == 1)) {
          message_ = com.panjin.grpc.errorhandling.CommodityQuote.getDefaultInstance();
        }
        comodityQuoteBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.panjin.grpc.errorhandling.CommodityQuote, com.panjin.grpc.errorhandling.CommodityQuote.Builder, com.panjin.grpc.errorhandling.CommodityQuoteOrBuilder>(
                (com.panjin.grpc.errorhandling.CommodityQuote) message_,
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      messageCase_ = 1;
      onChanged();
      return comodityQuoteBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.rpc.Status, com.google.rpc.Status.Builder, com.google.rpc.StatusOrBuilder> statusBuilder_;
    /**
     * <code>.google.rpc.Status status = 2;</code>
     * @return Whether the status field is set.
     */
    @java.lang.Override
    public boolean hasStatus() {
      return messageCase_ == 2;
    }
    /**
     * <code>.google.rpc.Status status = 2;</code>
     * @return The status.
     */
    @java.lang.Override
    public com.google.rpc.Status getStatus() {
      if (statusBuilder_ == null) {
        if (messageCase_ == 2) {
          return (com.google.rpc.Status) message_;
        }
        return com.google.rpc.Status.getDefaultInstance();
      } else {
        if (messageCase_ == 2) {
          return statusBuilder_.getMessage();
        }
        return com.google.rpc.Status.getDefaultInstance();
      }
    }
    /**
     * <code>.google.rpc.Status status = 2;</code>
     */
    public Builder setStatus(com.google.rpc.Status value) {
      if (statusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
        onChanged();
      } else {
        statusBuilder_.setMessage(value);
      }
      messageCase_ = 2;
      return this;
    }
    /**
     * <code>.google.rpc.Status status = 2;</code>
     */
    public Builder setStatus(
        com.google.rpc.Status.Builder builderForValue) {
      if (statusBuilder_ == null) {
        message_ = builderForValue.build();
        onChanged();
      } else {
        statusBuilder_.setMessage(builderForValue.build());
      }
      messageCase_ = 2;
      return this;
    }
    /**
     * <code>.google.rpc.Status status = 2;</code>
     */
    public Builder mergeStatus(com.google.rpc.Status value) {
      if (statusBuilder_ == null) {
        if (messageCase_ == 2 &&
            message_ != com.google.rpc.Status.getDefaultInstance()) {
          message_ = com.google.rpc.Status.newBuilder((com.google.rpc.Status) message_)
              .mergeFrom(value).buildPartial();
        } else {
          message_ = value;
        }
        onChanged();
      } else {
        if (messageCase_ == 2) {
          statusBuilder_.mergeFrom(value);
        } else {
          statusBuilder_.setMessage(value);
        }
      }
      messageCase_ = 2;
      return this;
    }
    /**
     * <code>.google.rpc.Status status = 2;</code>
     */
    public Builder clearStatus() {
      if (statusBuilder_ == null) {
        if (messageCase_ == 2) {
          messageCase_ = 0;
          message_ = null;
          onChanged();
        }
      } else {
        if (messageCase_ == 2) {
          messageCase_ = 0;
          message_ = null;
        }
        statusBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.google.rpc.Status status = 2;</code>
     */
    public com.google.rpc.Status.Builder getStatusBuilder() {
      return getStatusFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.rpc.Status status = 2;</code>
     */
    @java.lang.Override
    public com.google.rpc.StatusOrBuilder getStatusOrBuilder() {
      if ((messageCase_ == 2) && (statusBuilder_ != null)) {
        return statusBuilder_.getMessageOrBuilder();
      } else {
        if (messageCase_ == 2) {
          return (com.google.rpc.Status) message_;
        }
        return com.google.rpc.Status.getDefaultInstance();
      }
    }
    /**
     * <code>.google.rpc.Status status = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.rpc.Status, com.google.rpc.Status.Builder, com.google.rpc.StatusOrBuilder> 
        getStatusFieldBuilder() {
      if (statusBuilder_ == null) {
        if (!(messageCase_ == 2)) {
          message_ = com.google.rpc.Status.getDefaultInstance();
        }
        statusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.rpc.Status, com.google.rpc.Status.Builder, com.google.rpc.StatusOrBuilder>(
                (com.google.rpc.Status) message_,
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      messageCase_ = 2;
      onChanged();
      return statusBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:commodityprice.StreamingCommodityQuote)
  }

  // @@protoc_insertion_point(class_scope:commodityprice.StreamingCommodityQuote)
  private static final com.panjin.grpc.errorhandling.StreamingCommodityQuote DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.panjin.grpc.errorhandling.StreamingCommodityQuote();
  }

  public static com.panjin.grpc.errorhandling.StreamingCommodityQuote getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StreamingCommodityQuote>
      PARSER = new com.google.protobuf.AbstractParser<StreamingCommodityQuote>() {
    @java.lang.Override
    public StreamingCommodityQuote parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StreamingCommodityQuote> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StreamingCommodityQuote> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.panjin.grpc.errorhandling.StreamingCommodityQuote getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

