// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commodity_price.proto

package com.panjin.grpc.errorhandling;

public interface StreamingCommodityQuoteOrBuilder extends
    // @@protoc_insertion_point(interface_extends:commodityprice.StreamingCommodityQuote)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.commodityprice.CommodityQuote comodity_quote = 1;</code>
   * @return Whether the comodityQuote field is set.
   */
  boolean hasComodityQuote();
  /**
   * <code>.commodityprice.CommodityQuote comodity_quote = 1;</code>
   * @return The comodityQuote.
   */
  com.panjin.grpc.errorhandling.CommodityQuote getComodityQuote();
  /**
   * <code>.commodityprice.CommodityQuote comodity_quote = 1;</code>
   */
  com.panjin.grpc.errorhandling.CommodityQuoteOrBuilder getComodityQuoteOrBuilder();

  /**
   * <code>.google.rpc.Status status = 2;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <code>.google.rpc.Status status = 2;</code>
   * @return The status.
   */
  com.google.rpc.Status getStatus();
  /**
   * <code>.google.rpc.Status status = 2;</code>
   */
  com.google.rpc.StatusOrBuilder getStatusOrBuilder();

  public com.panjin.grpc.errorhandling.StreamingCommodityQuote.MessageCase getMessageCase();
}
