spring:
  cloud:
    stream:
      bindings:
        listen-in-0:
          destination: partitioned.destination
          group: myGroup
          consumer:
            partitioned: true
            instance-index: 0
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.16.101
                port: 5672
                username: root
                password: 123456

# 禁用rabbitMQ健康检查，因为RabbitHealthContributorAutoConfiguration会自动检查rabbitMQ的健康状态，且配置是从spring.rabbitmq中读取的，所以这里禁用
management:
  health:
    rabbit:
      enabled: false
server:
  port: 8081
