spring:
  rabbitmq:
    host: 192.168.16.101
    port: 5672
    username: root
    password: 123456
  cloud:
    stream:
      bindings:
        uppercase|echo-in-0:
          destination: uppercase-in
#          binder: rabbit
      function:
        definition: uppercase|echo
#      binders:
#        rabbit:
#          type: rabbit
#          environment:
#            spring:
#              rabbitmq:
#                host: 192.168.16.101
#                port: 5672
#                username: root
#                password: 123456