spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
  redis:
    host: 192.168.16.101
    port: 6379
  jpa:
    hibernate:
      # 如果不配置，默认是create-drop
      ddl-auto: update
    # 是否将DataSource初始化推迟到创建并初始化任何EntityManagerFactory bean之后。
    defer-datasource-initialization: true