// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stock_quote.proto

package com.panjin.grpc.streaming;

public final class StockQuoteProto {
  private StockQuoteProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stockquote_Stock_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stockquote_Stock_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stockquote_StockQuote_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stockquote_StockQuote_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021stock_quote.proto\022\nstockquote\"I\n\005Stock" +
      "\022\025\n\rticker_symbol\030\001 \001(\t\022\024\n\014company_name\030" +
      "\002 \001(\t\022\023\n\013description\030\003 \001(\t\"F\n\nStockQuote" +
      "\022\r\n\005price\030\001 \001(\001\022\024\n\014offer_number\030\002 \001(\005\022\023\n" +
      "\013description\030\003 \001(\t2\245\002\n\022StockQuoteProvide" +
      "r\022V\n%serverSideStreamingGetListStockQuot" +
      "es\022\021.stockquote.Stock\032\026.stockquote.Stock" +
      "Quote\"\0000\001\022Y\n(clientSideStreamingGetStati" +
      "sticsOfStocks\022\021.stockquote.Stock\032\026.stock" +
      "quote.StockQuote\"\000(\001\022\\\n)bidirectionalStr" +
      "eamingGetListsStockQuotes\022\021.stockquote.S" +
      "tock\032\026.stockquote.StockQuote\"\000(\0010\001B4\n\031co" +
      "m.panjin.grpc.streamingB\017StockQuoteProto" +
      "P\001\242\002\003RTGb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_stockquote_Stock_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_stockquote_Stock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stockquote_Stock_descriptor,
        new java.lang.String[] { "TickerSymbol", "CompanyName", "Description", });
    internal_static_stockquote_StockQuote_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_stockquote_StockQuote_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stockquote_StockQuote_descriptor,
        new java.lang.String[] { "Price", "OfferNumber", "Description", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
