// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stock_quote.proto

package com.panjin.grpc.streaming;

public interface StockQuoteOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stockquote.StockQuote)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double price = 1;</code>
   * @return The price.
   */
  double getPrice();

  /**
   * <code>int32 offer_number = 2;</code>
   * @return The offerNumber.
   */
  int getOfferNumber();

  /**
   * <code>string description = 3;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 3;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
